/*
Account Protect API

DataDome Account Protect API. Validate login, registration, account update, password update and custom events to detect and prevent account takeover, or collect events to enrich detection, and submit feedback on recommendations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// AuthenticationSocialProvider is an inline enum type for Authentication.SocialProvider.
type AuthenticationSocialProvider string

const (
	AuthenticationSocialProviderOther AuthenticationSocialProvider = "other"
	AuthenticationSocialProviderAmazon AuthenticationSocialProvider = "amazon"
	AuthenticationSocialProviderApple AuthenticationSocialProvider = "apple"
	AuthenticationSocialProviderFacebook AuthenticationSocialProvider = "facebook"
	AuthenticationSocialProviderGithub AuthenticationSocialProvider = "github"
	AuthenticationSocialProviderGoogle AuthenticationSocialProvider = "google"
	AuthenticationSocialProviderLinkedin AuthenticationSocialProvider = "linkedin"
	AuthenticationSocialProviderMicrosoft AuthenticationSocialProvider = "microsoft"
	AuthenticationSocialProviderTwitter AuthenticationSocialProvider = "twitter"
	AuthenticationSocialProviderYahoo AuthenticationSocialProvider = "yahoo"
)

// AuthenticationType is an inline enum type for Authentication.Type.
type AuthenticationType string

const (
	AuthenticationTypeLocal AuthenticationType = "local"
	AuthenticationTypeOther AuthenticationType = "other"
	AuthenticationTypeSocial AuthenticationType = "social"
)

// AuthenticationMode is an inline enum type for Authentication.Mode.
type AuthenticationMode string

const (
	AuthenticationModeOther AuthenticationMode = "other"
	AuthenticationModeBiometric AuthenticationMode = "biometric"
	AuthenticationModeMail AuthenticationMode = "mail"
	AuthenticationModeMfa AuthenticationMode = "mfa"
	AuthenticationModeOtp AuthenticationMode = "otp"
	AuthenticationModePassword AuthenticationMode = "password"
)

// Authentication Information about how the user authenticated
type Authentication struct {
	// Authentication social provider
	SocialProvider *AuthenticationSocialProvider `json:"socialProvider,omitempty"`
	// Authentication type
	Type *AuthenticationType `json:"type,omitempty"`
	// Authentication mode
	Mode *AuthenticationMode `json:"mode,omitempty"`
}

