/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// Payload Shared payload properties
type Payload struct {
	// User account (mail address, username, alias, login, ...)
	Account string `json:"account"`
	Module Module `json:"module"`
	Header Header `json:"header"`
	// For customers who sell their product as white label app, identify the partner using the solution to adapt detection models.
	PartnerId *string `json:"partnerId,omitempty"`
	// Custom business data fields for additional customer-specific information
	CustomFields []CustomField `json:"customFields,omitempty"`
}

func sanitizePayload(v *Payload) {
	v.Account = truncateValue(PayloadAccount, v.Account)
	sanitizeHeader(&v.Header)
	v.PartnerId = truncatePointerValue(PayloadPartnerId, v.PartnerId)
	if len(v.CustomFields) > 10 {
		v.CustomFields = v.CustomFields[:10]
	}
	for i := range v.CustomFields {
		sanitizeCustomField(&v.CustomFields[i])
	}
}


