/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// AuthenticationSocialProvider is an inline enum type for Authentication.SocialProvider.
type AuthenticationSocialProvider string

const (
	AuthenticationSocialProviderOther AuthenticationSocialProvider = "other"
	AuthenticationSocialProviderAmazon AuthenticationSocialProvider = "amazon"
	AuthenticationSocialProviderApple AuthenticationSocialProvider = "apple"
	AuthenticationSocialProviderFacebook AuthenticationSocialProvider = "facebook"
	AuthenticationSocialProviderGithub AuthenticationSocialProvider = "github"
	AuthenticationSocialProviderGoogle AuthenticationSocialProvider = "google"
	AuthenticationSocialProviderLinkedin AuthenticationSocialProvider = "linkedin"
	AuthenticationSocialProviderMicrosoft AuthenticationSocialProvider = "microsoft"
	AuthenticationSocialProviderTwitter AuthenticationSocialProvider = "twitter"
	AuthenticationSocialProviderYahoo AuthenticationSocialProvider = "yahoo"
)

// AuthenticationType is an inline enum type for Authentication.Type.
type AuthenticationType string

const (
	AuthenticationTypeLocal AuthenticationType = "local"
	AuthenticationTypeOther AuthenticationType = "other"
	AuthenticationTypeSocial AuthenticationType = "social"
)

// AuthenticationMode is an inline enum type for Authentication.Mode.
type AuthenticationMode string

const (
	AuthenticationModeOther AuthenticationMode = "other"
	AuthenticationModeBiometric AuthenticationMode = "biometric"
	AuthenticationModeMail AuthenticationMode = "mail"
	AuthenticationModeMfa AuthenticationMode = "mfa"
	AuthenticationModeOtp AuthenticationMode = "otp"
	AuthenticationModePassword AuthenticationMode = "password"
)

// Authentication struct for Authentication
type Authentication struct {
	// Authentication social provider
	SocialProvider *AuthenticationSocialProvider `json:"socialProvider,omitempty"`
	// Authentication type
	Type *AuthenticationType `json:"type,omitempty"`
	// Authentication mode
	Mode *AuthenticationMode `json:"mode,omitempty"`
}

