/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// FeedbackError Feedback error response
type FeedbackError struct {
	// Description of the error
	ErrorMessage string `json:"error"`
}
func (e *FeedbackError) Error() string { return e.ErrorMessage }

