/*
Account Protect API

DataDome Account Protect API. Validate login, registration, account update, password update and custom events to detect and prevent account takeover, or collect events to enrich detection, and submit feedback on recommendations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// PasswordUpdatePayloadAllOfUser struct for PasswordUpdatePayloadAllOfUser
type PasswordUpdatePayloadAllOfUser struct {
	// A unique customer identifier from your system. It has to be the same for all other event sent
	Id string `json:"id"`
}

func sanitizePasswordUpdatePayloadAllOfUser(v *PasswordUpdatePayloadAllOfUser) {
	v.Id = truncateValue(PasswordUpdatePayloadAllOfUserId, v.Id)
}


