/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// ResponseLogin struct for ResponseLogin
type ResponseLogin struct {
	Action ResponseAction `json:"action"`
	// List of models matching the event
	Reasons []string `json:"reasons,omitempty"`
	// Event identifier associated to this validate event (for both registration and login)
	EventId string `json:"eventId"`
	// The level of confidence when identifying a request as coming from a fraudster.
	Score *int `json:"score,omitempty"`
	// User IP
	Ip string `json:"ip"`
	Location Location `json:"location"`
	// Embeds the decoded API error (Message, Errors) when failing open, or nil on success.
	// When nil (normal response) the encoder skips all promoted fields automatically.
	*Error
}

