/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// FeedbackPayloadOneOfDecision is an inline enum type for FeedbackPayloadOneOf.Decision.
type FeedbackPayloadOneOfDecision string

const (
	FeedbackPayloadOneOfDecisionAllow FeedbackPayloadOneOfDecision = "allow"
	FeedbackPayloadOneOfDecisionChallenge FeedbackPayloadOneOfDecision = "challenge"
	FeedbackPayloadOneOfDecisionReview FeedbackPayloadOneOfDecision = "review"
	FeedbackPayloadOneOfDecisionDeny FeedbackPayloadOneOfDecision = "deny"
	FeedbackPayloadOneOfDecisionDelete FeedbackPayloadOneOfDecision = "delete"
)

// FeedbackPayloadOneOfOrigin is an inline enum type for FeedbackPayloadOneOf.Origin.
type FeedbackPayloadOneOfOrigin string

const (
	FeedbackPayloadOneOfOriginManualReview FeedbackPayloadOneOfOrigin = "manualReview"
	FeedbackPayloadOneOfOriginChargebacks FeedbackPayloadOneOfOrigin = "chargebacks"
	FeedbackPayloadOneOfOriginAutomatedRule FeedbackPayloadOneOfOrigin = "automatedRule"
	FeedbackPayloadOneOfOriginDashboard FeedbackPayloadOneOfOrigin = "dashboard"
	FeedbackPayloadOneOfOriginDatadome FeedbackPayloadOneOfOrigin = "datadome"
	FeedbackPayloadOneOfOriginOther FeedbackPayloadOneOfOrigin = "other"
)

// FeedbackPayloadOneOf struct for FeedbackPayloadOneOf
type FeedbackPayloadOneOf struct {
	// The decision that should have been taken for the event or account (mandatory).
	Decision FeedbackPayloadOneOfDecision `json:"decision"`
	// The timestamp (EPOCH in milliseconds) when the decision was taken.
	DecisionTime *int `json:"decisionTime,omitempty"`
	// The description of the reasons why a decision has been taken.
	DecisionReason *string `json:"decisionReason,omitempty"`
	// The system that triggers the decision (mandatory).
	Origin FeedbackPayloadOneOfOrigin `json:"origin"`
	// The id that identifies the decision-maker.
	OriginId *string `json:"originId,omitempty"`
	// The eventId of the event receiving a feedback. It should match the eventId returned by fraud SDK. This field is incompatible with account or userId but one of them is mandatory.
	EventId string `json:"eventId"`
}

