/*
Account Protect API

DataDome Account Protect API. Validate login, registration, account update, password update and custom events to detect and prevent account takeover, or collect events to enrich detection, and submit feedback on recommendations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// ErrorErrorsInner struct for ErrorErrorsInner
type ErrorErrorsInner struct {
	// Field name
	Field *string `json:"field,omitempty"`
	// Description of the error for this field
	Error *string `json:"error,omitempty"`
}

