/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// UserAllOfAddress Address of the user
type UserAllOfAddress struct {
	// Name of the address
	Name *string `json:"name,omitempty"`
	// line 1
	Line1 *string `json:"line1,omitempty"`
	// line 2
	Line2 *string `json:"line2,omitempty"`
	// City
	City *string `json:"city,omitempty"`
	// Country code, Format ISO-3166-1-alpha-2
	CountryCode *string `json:"countryCode,omitempty"`
	// Region code
	RegionCode *string `json:"regionCode,omitempty"`
	// Zip code
	ZipCode *string `json:"zipCode,omitempty"`
}

func sanitizeUserAllOfAddress(v *UserAllOfAddress) {
	v.Name = truncatePointerValue(UserAllOfAddressName, v.Name)
	v.Line1 = truncatePointerValue(UserAllOfAddressLine1, v.Line1)
	v.Line2 = truncatePointerValue(UserAllOfAddressLine2, v.Line2)
	v.City = truncatePointerValue(UserAllOfAddressCity, v.City)
	v.CountryCode = truncatePointerValue(UserAllOfAddressCountryCode, v.CountryCode)
	v.RegionCode = truncatePointerValue(UserAllOfAddressRegionCode, v.RegionCode)
	v.ZipCode = truncatePointerValue(UserAllOfAddressZipCode, v.ZipCode)
}


