/*
Account Protect API

DataDome Account Protect API. Validate login, registration, account update, password update and custom events to detect and prevent account takeover, or collect events to enrich detection, and submit feedback on recommendations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// Payload Shared payload properties
type Payload struct {
	// User account (mail address, username, alias, login, ...)
	Account string `json:"account"`
	Module Module `json:"module"`
	Header Header `json:"header"`
	// For customers who sell their product as white label app, identify the partner using the solution to adapt detection models.
	PartnerId *string `json:"partnerId,omitempty"`
	// Date when the event occurred on your side, if you send it later than it happened (for example from a queue). Format ISO 8601 YYYY-MM-DDThh:mm:ss.sssTZD. DataDome uses it to order the events. If eventDate is absent or has an invalid format, DataDome uses module.requestTimeMicros instead, and the event is still processed.
	EventDate *string `json:"eventDate,omitempty"`
	// Custom business data fields for additional customer-specific information
	CustomFields []CustomField `json:"customFields,omitempty"`
}

func sanitizePayload(v *Payload) {
	v.Account = truncateValue(PayloadAccount, v.Account)
	sanitizeHeader(&v.Header)
	v.PartnerId = truncatePointerValue(PayloadPartnerId, v.PartnerId)
	if len(v.CustomFields) > 10 {
		v.CustomFields = v.CustomFields[:10]
	}
	for i := range v.CustomFields {
		sanitizeCustomField(&v.CustomFields[i])
	}
}


