/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// LoginPayloadStatus is an inline enum type for LoginPayload.Status.
type LoginPayloadStatus string

const (
	LoginPayloadStatusFailed LoginPayloadStatus = "failed"
	LoginPayloadStatusSucceeded LoginPayloadStatus = "succeeded"
)

// LoginPayloadFailReason is an inline enum type for LoginPayload.FailReason.
type LoginPayloadFailReason string

const (
	LoginPayloadFailReasonUnknownAccount LoginPayloadFailReason = "unknownAccount"
	LoginPayloadFailReasonWrongPassword LoginPayloadFailReason = "wrongPassword"
	LoginPayloadFailReasonExpiredPassword LoginPayloadFailReason = "expiredPassword"
	LoginPayloadFailReasonDisabledAccount LoginPayloadFailReason = "disabledAccount"
	LoginPayloadFailReasonBlockedAccount LoginPayloadFailReason = "blockedAccount"
	LoginPayloadFailReasonInvalidMfa LoginPayloadFailReason = "invalidMfa"
	LoginPayloadFailReasonInternalBusinessRule LoginPayloadFailReason = "internalBusinessRule"
	LoginPayloadFailReasonTechnicalIssue LoginPayloadFailReason = "technicalIssue"
	LoginPayloadFailReasonOther LoginPayloadFailReason = "other"
)

// LoginPayload struct for LoginPayload
type LoginPayload struct {
	// User account (mail address, username, alias, login, ...)
	Account string `json:"account"`
	Module Module `json:"module"`
	Header Header `json:"header"`
	// For customers who sell their product as white label app, identify the partner using the solution to adapt detection models.
	PartnerId *string `json:"partnerId,omitempty"`
	// Custom business data fields for additional customer-specific information
	CustomFields []CustomField `json:"customFields,omitempty"`
	Session *Session `json:"session,omitempty"`
	// User login authentication status
	Status LoginPayloadStatus `json:"status"`
	// Reason why the login failed. Helps differentiate different types of fraud patterns.
	FailReason *LoginPayloadFailReason `json:"failReason,omitempty"`
	AccountType *AccountType `json:"accountType,omitempty"`
	// Date when account was created. Help improve detection for account created before Account Protect setup. Format ISO 8601 YYYY-MM-DDThh:mm:ssTZD
	AccountCreationDate *string `json:"accountCreationDate,omitempty"`
	User *LoginPayloadAllOfUser `json:"user,omitempty"`
	Authentication *LoginPayloadAllOfAuthentication `json:"authentication,omitempty"`
}

// LoginPayloadOption is a functional option for configuring optional [LoginPayload] fields.
type LoginPayloadOption func(*LoginPayload)

// LoginPayloadWithPartnerId sets the optional PartnerId field.
func LoginPayloadWithPartnerId(val string) (LoginPayloadOption, error) {
	val = truncateValue(LoginPayloadPartnerId, val)
	return func(p *LoginPayload) { p.PartnerId = &val }, nil
}

// LoginPayloadWithCustomFields sets the optional CustomFields field.
func LoginPayloadWithCustomFields(val []CustomField) LoginPayloadOption {
	for i := range val {
		sanitizeCustomField(&val[i])
	}
	if len(val) > 10 {
		val = val[:10]
	}
	return func(p *LoginPayload) { p.CustomFields = val }
}
// LoginPayloadWithSession sets the optional Session field.
func LoginPayloadWithSession(val Session) (LoginPayloadOption, error) {
	sanitizeSession(&val)
	return func(p *LoginPayload) { p.Session = &val }, nil
}

// LoginPayloadWithFailReason sets the optional FailReason field.
func LoginPayloadWithFailReason(val LoginPayloadFailReason) (LoginPayloadOption, error) {
	return func(p *LoginPayload) { p.FailReason = &val }, nil
}

// LoginPayloadWithAccountType sets the optional AccountType field.
func LoginPayloadWithAccountType(val AccountType) (LoginPayloadOption, error) {
	return func(p *LoginPayload) { p.AccountType = &val }, nil
}

// LoginPayloadWithAccountCreationDate sets the optional AccountCreationDate field.
func LoginPayloadWithAccountCreationDate(val string) (LoginPayloadOption, error) {
	return func(p *LoginPayload) { p.AccountCreationDate = &val }, nil
}

// LoginPayloadWithUser sets the optional User field.
func LoginPayloadWithUser(val LoginPayloadAllOfUser) (LoginPayloadOption, error) {
	sanitizeLoginPayloadAllOfUser(&val)
	return func(p *LoginPayload) { p.User = &val }, nil
}

// LoginPayloadWithAuthentication sets the optional Authentication field.
func LoginPayloadWithAuthentication(val LoginPayloadAllOfAuthentication) (LoginPayloadOption, error) {
	return func(p *LoginPayload) { p.Authentication = &val }, nil
}


