/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo

import "fmt"



// CustomActionPayloadEventStatus is an inline enum type for CustomActionPayload.EventStatus.
type CustomActionPayloadEventStatus string

const (
	CustomActionPayloadEventStatusAttempted CustomActionPayloadEventStatus = "attempted"
	CustomActionPayloadEventStatusSucceeded CustomActionPayloadEventStatus = "succeeded"
	CustomActionPayloadEventStatusFailed CustomActionPayloadEventStatus = "failed"
	CustomActionPayloadEventStatusExpired CustomActionPayloadEventStatus = "expired"
)

// CustomActionPayload Custom event payload sent from Customer endpoint to Account Protect server
type CustomActionPayload struct {
	Module Module `json:"module"`
	Header Header `json:"header"`
	// For customers who sell their product as white label app, identify the partner using the solution to adapt detection models.
	PartnerId *string `json:"partnerId,omitempty"`
	// Custom business data fields for additional customer-specific information
	CustomFields []CustomField `json:"customFields,omitempty"`
	// Name of the custom event in camelCase.
	EventName string `json:"eventName"`
	// Status of the custom event.
	EventStatus *CustomActionPayloadEventStatus `json:"eventStatus,omitempty"`
	// `true`: the action is linked to a sensitive behavior. `false` (default): the action is NOT linked to a sensitive behavior.
	IsEventCritical *bool `json:"isEventCritical,omitempty"`
	// Any raw text provided by the user. It can be a message content, a post, a ticket or any other relevant data to be checked by Account Protect. Content longer than 24544 bytes (UTF-8) is trimmed before storage. (PII)
	Content *string `json:"content,omitempty"`
	// The account related to the action. For example, if user A sends a message to user B, the value will be B. (PII)
	AccountTarget *string `json:"accountTarget,omitempty"`
	Session *Session `json:"session,omitempty"`
	AccountType *AccountType `json:"accountType,omitempty"`
	// Date when account was created. Help improve detection for account created before Account Protect setup. Format ISO 8601 YYYY-MM-DDThh:mm:ssTZD
	AccountCreationDate *string `json:"accountCreationDate,omitempty"`
	Authentication *Authentication `json:"authentication,omitempty"`
	// User account (mail address, username, alias, login, ...). Required if user.id is not provided. (PII)
	Account *string `json:"account,omitempty"`
	User *CustomActionPayloadAnyOf1AllOfUser `json:"user,omitempty"`
}

// CustomActionPayloadOption is a functional option for configuring optional [CustomActionPayload] fields.
type CustomActionPayloadOption func(*CustomActionPayload)

// CustomActionPayloadWithPartnerId sets the optional PartnerId field.
func CustomActionPayloadWithPartnerId(val string) (CustomActionPayloadOption, error) {
	val = truncateValue(CustomActionPayloadPartnerId, val)
	return func(p *CustomActionPayload) { p.PartnerId = &val }, nil
}

// CustomActionPayloadWithCustomFields sets the optional CustomFields field.
func CustomActionPayloadWithCustomFields(val []CustomField) CustomActionPayloadOption {
	for i := range val {
		sanitizeCustomField(&val[i])
	}
	if len(val) > 10 {
		val = val[:10]
	}
	return func(p *CustomActionPayload) { p.CustomFields = val }
}
// CustomActionPayloadWithEventStatus sets the optional EventStatus field.
func CustomActionPayloadWithEventStatus(val CustomActionPayloadEventStatus) (CustomActionPayloadOption, error) {
	return func(p *CustomActionPayload) { p.EventStatus = &val }, nil
}

// CustomActionPayloadWithIsEventCritical sets the optional IsEventCritical field.
func CustomActionPayloadWithIsEventCritical(val bool) (CustomActionPayloadOption, error) {
	return func(p *CustomActionPayload) { p.IsEventCritical = &val }, nil
}

// CustomActionPayloadWithContent sets the optional Content field.
func CustomActionPayloadWithContent(val string) (CustomActionPayloadOption, error) {
	val = truncateValue(CustomActionPayloadContent, val)
	return func(p *CustomActionPayload) { p.Content = &val }, nil
}

// CustomActionPayloadWithAccountTarget sets the optional AccountTarget field.
func CustomActionPayloadWithAccountTarget(val string) (CustomActionPayloadOption, error) {
	val = truncateValue(CustomActionPayloadAccountTarget, val)
	return func(p *CustomActionPayload) { p.AccountTarget = &val }, nil
}

// CustomActionPayloadWithSession sets the optional Session field.
func CustomActionPayloadWithSession(val Session) (CustomActionPayloadOption, error) {
	sanitizeSession(&val)
	return func(p *CustomActionPayload) { p.Session = &val }, nil
}

// CustomActionPayloadWithAccountType sets the optional AccountType field.
func CustomActionPayloadWithAccountType(val AccountType) (CustomActionPayloadOption, error) {
	return func(p *CustomActionPayload) { p.AccountType = &val }, nil
}

// CustomActionPayloadWithAccountCreationDate sets the optional AccountCreationDate field.
func CustomActionPayloadWithAccountCreationDate(val string) (CustomActionPayloadOption, error) {
	return func(p *CustomActionPayload) { p.AccountCreationDate = &val }, nil
}

// CustomActionPayloadWithAuthentication sets the optional Authentication field.
func CustomActionPayloadWithAuthentication(val Authentication) (CustomActionPayloadOption, error) {
	return func(p *CustomActionPayload) { p.Authentication = &val }, nil
}

// CustomActionPayloadWithAccount sets the optional Account field.
func CustomActionPayloadWithAccount(val string) (CustomActionPayloadOption, error) {
	if len(val) < 1 {
		return nil, fmt.Errorf("account: value must be at least 1 character(s)")
	}
	val = truncateValue(CustomActionPayloadAccount, val)
	return func(p *CustomActionPayload) { p.Account = &val }, nil
}

// CustomActionPayloadWithUser sets the optional User field.
func CustomActionPayloadWithUser(val CustomActionPayloadAnyOf1AllOfUser) (CustomActionPayloadOption, error) {
	sanitizeCustomActionPayloadAnyOf1AllOfUser(&val)
	return func(p *CustomActionPayload) { p.User = &val }, nil
}


