/*
Account Protect API

DataDome Account Protect API. Validate login, registration, account update, password update and custom events to detect and prevent account takeover, or collect events to enrich detection, and submit feedback on recommendations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// FeedbackError Feedback error response
type FeedbackError struct {
	// Description of the error
	ErrorMessage string `json:"error"`
}
func (e *FeedbackError) Error() string { return e.ErrorMessage }

