/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// CustomActionPayloadAnyOf1EventStatus is an inline enum type for CustomActionPayloadAnyOf1.EventStatus.
type CustomActionPayloadAnyOf1EventStatus string

const (
	CustomActionPayloadAnyOf1EventStatusAttempted CustomActionPayloadAnyOf1EventStatus = "attempted"
	CustomActionPayloadAnyOf1EventStatusSucceeded CustomActionPayloadAnyOf1EventStatus = "succeeded"
	CustomActionPayloadAnyOf1EventStatusFailed CustomActionPayloadAnyOf1EventStatus = "failed"
	CustomActionPayloadAnyOf1EventStatusExpired CustomActionPayloadAnyOf1EventStatus = "expired"
)

// CustomActionPayloadAnyOf1 struct for CustomActionPayloadAnyOf1
type CustomActionPayloadAnyOf1 struct {
	Module Module `json:"module"`
	Header Header `json:"header"`
	// For customers who sell their product as white label app, identify the partner using the solution to adapt detection models.
	PartnerId *string `json:"partnerId,omitempty"`
	// Custom business data fields for additional customer-specific information
	CustomFields []CustomField `json:"customFields,omitempty"`
	// Name of the custom event in camelCase.
	EventName string `json:"eventName"`
	// Status of the custom event.
	EventStatus *CustomActionPayloadAnyOf1EventStatus `json:"eventStatus,omitempty"`
	// `true`: the action is linked to a sensitive behavior. `false` (default): the action is NOT linked to a sensitive behavior.
	IsEventCritical *bool `json:"isEventCritical,omitempty"`
	// Any raw text provided by the user. It can be a message content, a post, a ticket or any other relevant data to be checked by Account Protect. Content longer than 24544 bytes (UTF-8) is trimmed before storage. (PII)
	Content *string `json:"content,omitempty"`
	// The account related to the action. For example, if user A sends a message to user B, the value will be B. (PII)
	AccountTarget *string `json:"accountTarget,omitempty"`
	Session *Session `json:"session,omitempty"`
	AccountType *AccountType `json:"accountType,omitempty"`
	// Date when account was created. Help improve detection for account created before Account Protect setup. Format ISO 8601 YYYY-MM-DDThh:mm:ssTZD
	AccountCreationDate *string `json:"accountCreationDate,omitempty"`
	Authentication *Authentication `json:"authentication,omitempty"`
	User CustomActionPayloadAnyOf1AllOfUser `json:"user"`
}

func sanitizeCustomActionPayloadAnyOf1(v *CustomActionPayloadAnyOf1) {
	sanitizeHeader(&v.Header)
	v.PartnerId = truncatePointerValue(CustomActionPayloadAnyOf1PartnerId, v.PartnerId)
	if len(v.CustomFields) > 10 {
		v.CustomFields = v.CustomFields[:10]
	}
	for i := range v.CustomFields {
		sanitizeCustomField(&v.CustomFields[i])
	}
	v.EventName = truncateValue(CustomActionPayloadAnyOf1EventName, v.EventName)
	v.Content = truncatePointerValue(CustomActionPayloadAnyOf1Content, v.Content)
	v.AccountTarget = truncatePointerValue(CustomActionPayloadAnyOf1AccountTarget, v.AccountTarget)
	if v.Session != nil {
		sanitizeSession(v.Session)
	}
	sanitizeCustomActionPayloadAnyOf1AllOfUser(&v.User)
}


