/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// LoginPayloadAllOfUser struct for LoginPayloadAllOfUser
type LoginPayloadAllOfUser struct {
	// A unique customer identifier from your system. It has to be the same for all other event sent
	Id *string `json:"id,omitempty"`
}

func sanitizeLoginPayloadAllOfUser(v *LoginPayloadAllOfUser) {
	v.Id = truncatePointerValue(LoginPayloadAllOfUserId, v.Id)
}


