/*
Account Protect API

DataDome Account Protect API. Validate login, registration, account update, password update and custom events to detect and prevent account takeover, or collect events to enrich detection, and submit feedback on recommendations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// Module Information about module sending this Payload
type Module struct {
	// Timestamp of the request, in microseconds
	RequestTimeMicros int64 `json:"requestTimeMicros"`
	// Module name
	Name string `json:"name"`
	// Module version
	Version string `json:"version"`
}

