/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// Response Validate response from Account Protect server to Customer endpoint
type Response struct {
	Action ResponseAction `json:"action"`
	// List of models matching the event
	Reasons []string `json:"reasons,omitempty"`
	// Event identifier associated to this validate event (for both registration and login)
	EventId string `json:"eventId"`
	// The level of confidence when identifying a request as coming from a fraudster.
	Score *int `json:"score,omitempty"`
	// Embeds the decoded API error (Message, Errors) when failing open, or nil on success.
	// When nil (normal response) the encoder skips all promoted fields automatically.
	*Error
}

