/*
Account Protect API

DataDome Account Protect API. Validate login, registration, account update, password update and custom events to detect and prevent account takeover, or collect events to enrich detection, and submit feedback on recommendations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// RegistrationPayloadAllOfAuthentication struct for RegistrationPayloadAllOfAuthentication
type RegistrationPayloadAllOfAuthentication struct {
	SocialProvider interface{} `json:"socialProvider,omitempty"`
	Type interface{} `json:"type,omitempty"`
	Mode interface{} `json:"mode,omitempty"`
}

