/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// ErrorErrorsInner struct for ErrorErrorsInner
type ErrorErrorsInner struct {
	// Field name
	Field *string `json:"field,omitempty"`
	// Description of the error for this field
	Error *string `json:"error,omitempty"`
}

