/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// AccountUpdatePayload struct for AccountUpdatePayload
type AccountUpdatePayload struct {
	// User account (mail address, username, alias, login, ...)
	Account string `json:"account"`
	Module Module `json:"module"`
	Header Header `json:"header"`
	// For customers who sell their product as white label app, identify the partner using the solution to adapt detection models.
	PartnerId *string `json:"partnerId,omitempty"`
	// Custom business data fields for additional customer-specific information
	CustomFields []CustomField `json:"customFields,omitempty"`
	Session *Session `json:"session,omitempty"`
	AccountType *AccountType `json:"accountType,omitempty"`
	// Date when account was created. Help improve detection for account created before Account Protect setup. Format ISO 8601 YYYY-MM-DDThh:mm:ssTZD
	AccountCreationDate *string `json:"accountCreationDate,omitempty"`
	User *AccountUpdatePayloadAllOfUser `json:"user,omitempty"`
	Authentication *AccountUpdatePayloadAllOfAuthentication `json:"authentication,omitempty"`
}

// AccountUpdatePayloadOption is a functional option for configuring optional [AccountUpdatePayload] fields.
type AccountUpdatePayloadOption func(*AccountUpdatePayload)

// AccountUpdatePayloadWithPartnerId sets the optional PartnerId field.
func AccountUpdatePayloadWithPartnerId(val string) (AccountUpdatePayloadOption, error) {
	val = truncateValue(AccountUpdatePayloadPartnerId, val)
	return func(p *AccountUpdatePayload) { p.PartnerId = &val }, nil
}

// AccountUpdatePayloadWithCustomFields sets the optional CustomFields field.
func AccountUpdatePayloadWithCustomFields(val []CustomField) AccountUpdatePayloadOption {
	for i := range val {
		sanitizeCustomField(&val[i])
	}
	if len(val) > 10 {
		val = val[:10]
	}
	return func(p *AccountUpdatePayload) { p.CustomFields = val }
}
// AccountUpdatePayloadWithSession sets the optional Session field.
func AccountUpdatePayloadWithSession(val Session) (AccountUpdatePayloadOption, error) {
	sanitizeSession(&val)
	return func(p *AccountUpdatePayload) { p.Session = &val }, nil
}

// AccountUpdatePayloadWithAccountType sets the optional AccountType field.
func AccountUpdatePayloadWithAccountType(val AccountType) (AccountUpdatePayloadOption, error) {
	return func(p *AccountUpdatePayload) { p.AccountType = &val }, nil
}

// AccountUpdatePayloadWithAccountCreationDate sets the optional AccountCreationDate field.
func AccountUpdatePayloadWithAccountCreationDate(val string) (AccountUpdatePayloadOption, error) {
	return func(p *AccountUpdatePayload) { p.AccountCreationDate = &val }, nil
}

// AccountUpdatePayloadWithUser sets the optional User field.
func AccountUpdatePayloadWithUser(val AccountUpdatePayloadAllOfUser) (AccountUpdatePayloadOption, error) {
	sanitizeAccountUpdatePayloadAllOfUser(&val)
	return func(p *AccountUpdatePayload) { p.User = &val }, nil
}

// AccountUpdatePayloadWithAuthentication sets the optional Authentication field.
func AccountUpdatePayloadWithAuthentication(val AccountUpdatePayloadAllOfAuthentication) (AccountUpdatePayloadOption, error) {
	return func(p *AccountUpdatePayload) { p.Authentication = &val }, nil
}


