/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// Location User Location
type Location struct {
	// Country code, format ISO-3166-1-alpha-2
	CountryCode *string `json:"countryCode,omitempty"`
	// Country name
	Country *string `json:"country,omitempty"`
	// City
	City *string `json:"city,omitempty"`
}

