/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// FeedbackPayloadBaseDecision is an inline enum type for FeedbackPayloadBase.Decision.
type FeedbackPayloadBaseDecision string

const (
	FeedbackPayloadBaseDecisionAllow FeedbackPayloadBaseDecision = "allow"
	FeedbackPayloadBaseDecisionChallenge FeedbackPayloadBaseDecision = "challenge"
	FeedbackPayloadBaseDecisionReview FeedbackPayloadBaseDecision = "review"
	FeedbackPayloadBaseDecisionDeny FeedbackPayloadBaseDecision = "deny"
	FeedbackPayloadBaseDecisionDelete FeedbackPayloadBaseDecision = "delete"
)

// FeedbackPayloadBaseOrigin is an inline enum type for FeedbackPayloadBase.Origin.
type FeedbackPayloadBaseOrigin string

const (
	FeedbackPayloadBaseOriginManualReview FeedbackPayloadBaseOrigin = "manualReview"
	FeedbackPayloadBaseOriginChargebacks FeedbackPayloadBaseOrigin = "chargebacks"
	FeedbackPayloadBaseOriginAutomatedRule FeedbackPayloadBaseOrigin = "automatedRule"
	FeedbackPayloadBaseOriginDashboard FeedbackPayloadBaseOrigin = "dashboard"
	FeedbackPayloadBaseOriginDatadome FeedbackPayloadBaseOrigin = "datadome"
	FeedbackPayloadBaseOriginOther FeedbackPayloadBaseOrigin = "other"
)

// FeedbackPayloadBase Base properties for feedback payload sent to Account Protect server
type FeedbackPayloadBase struct {
	// The decision that should have been taken for the event or account (mandatory).
	Decision FeedbackPayloadBaseDecision `json:"decision"`
	// The timestamp (EPOCH in milliseconds) when the decision was taken.
	DecisionTime *int `json:"decisionTime,omitempty"`
	// The description of the reasons why a decision has been taken.
	DecisionReason *string `json:"decisionReason,omitempty"`
	// The system that triggers the decision (mandatory).
	Origin FeedbackPayloadBaseOrigin `json:"origin"`
	// The id that identifies the decision-maker.
	OriginId *string `json:"originId,omitempty"`
}

