/*
Account Protect API

DataDome Account Protect API. Validate login, registration, account update, password update and custom events to detect and prevent account takeover, or collect events to enrich detection, and submit feedback on recommendations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// Feedback400Response struct for Feedback400Response
type Feedback400Response struct {
	// Description of the error
	Message string `json:"message"`
	// List of the fields in error
	Errors []ErrorErrorsInner `json:"errors"`
	// Description of the error
	ErrorMessage string `json:"error"`
}
func (e *Feedback400Response) Error() string { return e.Message }

