/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// Session Information about the user session
type Session struct {
	// A unique session identifier from your system
	Id *string `json:"id,omitempty"`
	// Creation date of the session, Format ISO 8601 YYYY-MM-DDThh:mm:ssTZD
	CreatedAt *string `json:"createdAt,omitempty"`
}

func sanitizeSession(v *Session) {
	v.Id = truncatePointerValue(SessionId, v.Id)
}


