/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// AccountUpdatePayloadAllOfUser struct for AccountUpdatePayloadAllOfUser
type AccountUpdatePayloadAllOfUser struct {
	// A unique customer identifier from your system. It has to be the same for all other event sent
	Id *string `json:"id,omitempty"`
	Title *UserTitle `json:"title,omitempty"`
	// First name of the user
	FirstName *string `json:"firstName,omitempty"`
	// Last name of the user
	LastName *string `json:"lastName,omitempty"`
	// Creation date of the user, Format ISO 8601 YYYY-MM-DDThh:mm:ssTZD
	CreatedAt *string `json:"createdAt,omitempty"`
	// Phone of the user, E.164 format including + and a region code, for example +33978787878
	Phone *string `json:"phone,omitempty"`
	// Email of the user
	Email *string `json:"email,omitempty"`
	// Display name of the user
	DisplayName *string `json:"displayName,omitempty"`
	// Description or biography of the user
	Description *string `json:"description,omitempty"`
	// Pictures of the user
	PictureUrls []string `json:"pictureUrls,omitempty"`
	// External URLs of the user
	ExternalUrls []string `json:"externalUrls,omitempty"`
	Address *UserAllOfAddress `json:"address,omitempty"`
	// Date of birth of the user used to estimate its age and adapt detection models. Format ISO 8601 YYYY-MM-DDThh:mm:ssTZD (PII)
	DateOfBirth *string `json:"dateOfBirth,omitempty"`
	// Payment method updated
	PaymentMethodUpdated *bool `json:"paymentMethodUpdated,omitempty"`
}

func sanitizeAccountUpdatePayloadAllOfUser(v *AccountUpdatePayloadAllOfUser) {
	v.Id = truncatePointerValue(AccountUpdatePayloadAllOfUserId, v.Id)
	v.FirstName = truncatePointerValue(AccountUpdatePayloadAllOfUserFirstName, v.FirstName)
	v.LastName = truncatePointerValue(AccountUpdatePayloadAllOfUserLastName, v.LastName)
	v.Phone = truncatePointerValue(AccountUpdatePayloadAllOfUserPhone, v.Phone)
	v.Email = truncatePointerValue(AccountUpdatePayloadAllOfUserEmail, v.Email)
	v.DisplayName = truncatePointerValue(AccountUpdatePayloadAllOfUserDisplayName, v.DisplayName)
	v.Description = truncatePointerValue(AccountUpdatePayloadAllOfUserDescription, v.Description)
	v.PictureUrls = capAndTruncateStrings(v.PictureUrls, MaxAccountUpdatePayloadAllOfUserPictureUrls, AccountUpdatePayloadAllOfUserPictureUrlsItem)
	v.ExternalUrls = capAndTruncateStrings(v.ExternalUrls, MaxAccountUpdatePayloadAllOfUserExternalUrls, AccountUpdatePayloadAllOfUserExternalUrlsItem)
	if v.Address != nil {
		sanitizeUserAllOfAddress(v.Address)
	}
}


