/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// PasswordUpdatePayloadAllOfAuthentication struct for PasswordUpdatePayloadAllOfAuthentication
type PasswordUpdatePayloadAllOfAuthentication struct {
	SocialProvider interface{} `json:"socialProvider,omitempty"`
	Type interface{} `json:"type,omitempty"`
	Mode interface{} `json:"mode,omitempty"`
}

