/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// Module Information about module sending this Payload
type Module struct {
	// Timestamp of the request, in microseconds
	RequestTimeMicros int64 `json:"requestTimeMicros"`
	// Module name
	Name string `json:"name"`
	// Module version
	Version string `json:"version"`
}

