/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// Feedback201Response Contains the feedback&#39;s ID associated to the feedback created
type Feedback201Response struct {
	// The feedback's ID, needed for any support request
	FeedbackId *string `json:"feedbackId,omitempty"`
}

