/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// Error Error response
type Error struct {
	// Description of the error
	Message string `json:"message"`
	// List of the fields in error
	Errors []ErrorErrorsInner `json:"errors"`
}
func (e *Error) Error() string { return e.Message }

