/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo



// UserTitle Title of the user
type UserTitle string

// List of UserTitle
const (
	MR UserTitle = "mr"
	MRS UserTitle = "mrs"
	MX UserTitle = "mx"
)

