/*
Account Protect API

DataDome Account Protect API. Validate login, registration, account update, password update and custom events to detect and prevent account takeover, or collect events to enrich detection, and submit feedback on recommendations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// PasswordUpdatePayloadReason is an inline enum type for PasswordUpdatePayload.Reason.
type PasswordUpdatePayloadReason string

const (
	PasswordUpdatePayloadReasonForcedReset PasswordUpdatePayloadReason = "forcedReset"
	PasswordUpdatePayloadReasonForgotPassword PasswordUpdatePayloadReason = "forgotPassword"
	PasswordUpdatePayloadReasonUserUpdate PasswordUpdatePayloadReason = "userUpdate"
)

// PasswordUpdatePayloadStatus is an inline enum type for PasswordUpdatePayload.Status.
type PasswordUpdatePayloadStatus string

const (
	PasswordUpdatePayloadStatusAttempted PasswordUpdatePayloadStatus = "attempted"
	PasswordUpdatePayloadStatusFailed PasswordUpdatePayloadStatus = "failed"
	PasswordUpdatePayloadStatusSucceeded PasswordUpdatePayloadStatus = "succeeded"
	PasswordUpdatePayloadStatusLinkExpired PasswordUpdatePayloadStatus = "linkExpired"
)

// PasswordUpdatePayload struct for PasswordUpdatePayload
type PasswordUpdatePayload struct {
	// User account (mail address, username, alias, login, ...)
	Account string `json:"account"`
	Module Module `json:"module"`
	Header Header `json:"header"`
	// For customers who sell their product as white label app, identify the partner using the solution to adapt detection models.
	PartnerId *string `json:"partnerId,omitempty"`
	// Date when the event occurred on your side, if you send it later than it happened (for example from a queue). Format ISO 8601 YYYY-MM-DDThh:mm:ss.sssTZD. DataDome uses it to order the events. If eventDate is absent or has an invalid format, DataDome uses module.requestTimeMicros instead, and the event is still processed.
	EventDate *string `json:"eventDate,omitempty"`
	// Custom business data fields for additional customer-specific information
	CustomFields []CustomField `json:"customFields,omitempty"`
	// Reason for the password change
	Reason PasswordUpdatePayloadReason `json:"reason"`
	// Status of the password change
	Status PasswordUpdatePayloadStatus `json:"status"`
	// Date when account was created. Help improve detection for account created before Account Protect setup. Format ISO 8601 YYYY-MM-DDThh:mm:ssTZD
	AccountCreationDate *string `json:"accountCreationDate,omitempty"`
	Session *Session `json:"session,omitempty"`
	User PasswordUpdatePayloadAllOfUser `json:"user"`
	Authentication *PasswordUpdatePayloadAllOfAuthentication `json:"authentication,omitempty"`
}

// PasswordUpdatePayloadOption is a functional option for configuring optional [PasswordUpdatePayload] fields.
type PasswordUpdatePayloadOption func(*PasswordUpdatePayload)

// PasswordUpdatePayloadWithPartnerId sets the optional PartnerId field.
func PasswordUpdatePayloadWithPartnerId(val string) (PasswordUpdatePayloadOption, error) {
	val = truncateValue(PasswordUpdatePayloadPartnerId, val)
	return func(p *PasswordUpdatePayload) { p.PartnerId = &val }, nil
}

// PasswordUpdatePayloadWithEventDate sets the optional EventDate field.
func PasswordUpdatePayloadWithEventDate(val string) (PasswordUpdatePayloadOption, error) {
	return func(p *PasswordUpdatePayload) { p.EventDate = &val }, nil
}

// PasswordUpdatePayloadWithCustomFields sets the optional CustomFields field.
func PasswordUpdatePayloadWithCustomFields(val []CustomField) PasswordUpdatePayloadOption {
	for i := range val {
		sanitizeCustomField(&val[i])
	}
	if len(val) > 10 {
		val = val[:10]
	}
	return func(p *PasswordUpdatePayload) { p.CustomFields = val }
}
// PasswordUpdatePayloadWithAccountCreationDate sets the optional AccountCreationDate field.
func PasswordUpdatePayloadWithAccountCreationDate(val string) (PasswordUpdatePayloadOption, error) {
	return func(p *PasswordUpdatePayload) { p.AccountCreationDate = &val }, nil
}

// PasswordUpdatePayloadWithSession sets the optional Session field.
func PasswordUpdatePayloadWithSession(val Session) (PasswordUpdatePayloadOption, error) {
	sanitizeSession(&val)
	return func(p *PasswordUpdatePayload) { p.Session = &val }, nil
}

// PasswordUpdatePayloadWithAuthentication sets the optional Authentication field.
func PasswordUpdatePayloadWithAuthentication(val PasswordUpdatePayloadAllOfAuthentication) (PasswordUpdatePayloadOption, error) {
	return func(p *PasswordUpdatePayload) { p.Authentication = &val }, nil
}


