/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo



// ResponseAction Action answered to Customer endpoint
type ResponseAction string

// List of ResponseAction
const (
	DENY ResponseAction = "deny"
	REVIEW ResponseAction = "review"
	CHALLENGE ResponseAction = "challenge"
	ALLOW ResponseAction = "allow"
)

