/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// FeedbackPayloadOneOf1Decision is an inline enum type for FeedbackPayloadOneOf1.Decision.
type FeedbackPayloadOneOf1Decision string

const (
	FeedbackPayloadOneOf1DecisionAllow FeedbackPayloadOneOf1Decision = "allow"
	FeedbackPayloadOneOf1DecisionChallenge FeedbackPayloadOneOf1Decision = "challenge"
	FeedbackPayloadOneOf1DecisionReview FeedbackPayloadOneOf1Decision = "review"
	FeedbackPayloadOneOf1DecisionDeny FeedbackPayloadOneOf1Decision = "deny"
	FeedbackPayloadOneOf1DecisionDelete FeedbackPayloadOneOf1Decision = "delete"
)

// FeedbackPayloadOneOf1Origin is an inline enum type for FeedbackPayloadOneOf1.Origin.
type FeedbackPayloadOneOf1Origin string

const (
	FeedbackPayloadOneOf1OriginManualReview FeedbackPayloadOneOf1Origin = "manualReview"
	FeedbackPayloadOneOf1OriginChargebacks FeedbackPayloadOneOf1Origin = "chargebacks"
	FeedbackPayloadOneOf1OriginAutomatedRule FeedbackPayloadOneOf1Origin = "automatedRule"
	FeedbackPayloadOneOf1OriginDashboard FeedbackPayloadOneOf1Origin = "dashboard"
	FeedbackPayloadOneOf1OriginDatadome FeedbackPayloadOneOf1Origin = "datadome"
	FeedbackPayloadOneOf1OriginOther FeedbackPayloadOneOf1Origin = "other"
)

// FeedbackPayloadOneOf1 struct for FeedbackPayloadOneOf1
type FeedbackPayloadOneOf1 struct {
	// The decision that should have been taken for the event or account (mandatory).
	Decision FeedbackPayloadOneOf1Decision `json:"decision"`
	// The timestamp (EPOCH in milliseconds) when the decision was taken.
	DecisionTime *int `json:"decisionTime,omitempty"`
	// The description of the reasons why a decision has been taken.
	DecisionReason *string `json:"decisionReason,omitempty"`
	// The system that triggers the decision (mandatory).
	Origin FeedbackPayloadOneOf1Origin `json:"origin"`
	// The id that identifies the decision-maker.
	OriginId *string `json:"originId,omitempty"`
	// The account of the user receiving a feedback. It should match the field account sent in fraud SDK request. This field is incompatible with eventId or userId but one of them is mandatory.
	Account string `json:"account"`
}

