/*
Account Protect API

DataDome Account Protect API. Validate login, registration, account update, password update and custom events to detect and prevent account takeover, or collect events to enrich detection, and submit feedback on recommendations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// Response Validate response from Account Protect server to Customer endpoint
type Response struct {
	Action ResponseAction `json:"action"`
	// List of models matching the event
	Reasons []string `json:"reasons,omitempty"`
	// Event identifier associated to this validate event (for both registration and login)
	EventId string `json:"eventId"`
	// The level of confidence when identifying a request as coming from a fraudster.
	Score *int `json:"score,omitempty"`
	// Embeds the decoded API error (Message, Errors) when failing open, or nil on success.
	// When nil (normal response) the encoder skips all promoted fields automatically.
	*Error
}

