/*
Account Protect API

DataDome Account Protect API. Validate login, registration, account update, password update and custom events to detect and prevent account takeover, or collect events to enrich detection, and submit feedback on recommendations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// Location User Location
type Location struct {
	// Country code, format ISO-3166-1-alpha-2
	CountryCode *string `json:"countryCode,omitempty"`
	// Country name
	Country *string `json:"country,omitempty"`
	// City
	City *string `json:"city,omitempty"`
}

