/*
Account Protect API

DataDome Account Protect API. Validate login, registration, account update, password update and custom events to detect and prevent account takeover, or collect events to enrich detection, and submit feedback on recommendations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo



// AccountType Type of the account to adapt detection model on the user type
type AccountType string

// List of AccountType
const (
	GUEST AccountType = "guest"
	STAFF AccountType = "staff"
	EXTERNAL AccountType = "external"
	PARTNER AccountType = "partner"
	CUSTOMER AccountType = "customer"
	MERCHANT AccountType = "merchant"
	VIP AccountType = "vip"
	TEST AccountType = "test"
	OTHER AccountType = "other"
)

