/*
Account Protect API

DataDome Account Protect API. Validate login, registration, account update, password update and custom events to detect and prevent account takeover, or collect events to enrich detection, and submit feedback on recommendations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// Feedback201Response Contains the feedback&#39;s ID associated to the feedback created
type Feedback201Response struct {
	// The feedback's ID, needed for any support request
	FeedbackId *string `json:"feedbackId,omitempty"`
}

