/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// FeedbackPayloadOneOf2Decision is an inline enum type for FeedbackPayloadOneOf2.Decision.
type FeedbackPayloadOneOf2Decision string

const (
	FeedbackPayloadOneOf2DecisionAllow FeedbackPayloadOneOf2Decision = "allow"
	FeedbackPayloadOneOf2DecisionChallenge FeedbackPayloadOneOf2Decision = "challenge"
	FeedbackPayloadOneOf2DecisionReview FeedbackPayloadOneOf2Decision = "review"
	FeedbackPayloadOneOf2DecisionDeny FeedbackPayloadOneOf2Decision = "deny"
	FeedbackPayloadOneOf2DecisionDelete FeedbackPayloadOneOf2Decision = "delete"
)

// FeedbackPayloadOneOf2Origin is an inline enum type for FeedbackPayloadOneOf2.Origin.
type FeedbackPayloadOneOf2Origin string

const (
	FeedbackPayloadOneOf2OriginManualReview FeedbackPayloadOneOf2Origin = "manualReview"
	FeedbackPayloadOneOf2OriginChargebacks FeedbackPayloadOneOf2Origin = "chargebacks"
	FeedbackPayloadOneOf2OriginAutomatedRule FeedbackPayloadOneOf2Origin = "automatedRule"
	FeedbackPayloadOneOf2OriginDashboard FeedbackPayloadOneOf2Origin = "dashboard"
	FeedbackPayloadOneOf2OriginDatadome FeedbackPayloadOneOf2Origin = "datadome"
	FeedbackPayloadOneOf2OriginOther FeedbackPayloadOneOf2Origin = "other"
)

// FeedbackPayloadOneOf2 struct for FeedbackPayloadOneOf2
type FeedbackPayloadOneOf2 struct {
	// The decision that should have been taken for the event or account (mandatory).
	Decision FeedbackPayloadOneOf2Decision `json:"decision"`
	// The timestamp (EPOCH in milliseconds) when the decision was taken.
	DecisionTime *int `json:"decisionTime,omitempty"`
	// The description of the reasons why a decision has been taken.
	DecisionReason *string `json:"decisionReason,omitempty"`
	// The system that triggers the decision (mandatory).
	Origin FeedbackPayloadOneOf2Origin `json:"origin"`
	// The id that identifies the decision-maker.
	OriginId *string `json:"originId,omitempty"`
	// The userId of the user receiving a feedback. It should match the field userId sent in fraud SDK request. This field is incompatible with eventId or account but one of them is mandatory.
	UserId string `json:"userId"`
}

