/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// FeedbackPayloadDecision is an inline enum type for FeedbackPayload.Decision.
type FeedbackPayloadDecision string

const (
	FeedbackPayloadDecisionAllow FeedbackPayloadDecision = "allow"
	FeedbackPayloadDecisionChallenge FeedbackPayloadDecision = "challenge"
	FeedbackPayloadDecisionReview FeedbackPayloadDecision = "review"
	FeedbackPayloadDecisionDeny FeedbackPayloadDecision = "deny"
	FeedbackPayloadDecisionDelete FeedbackPayloadDecision = "delete"
)

// FeedbackPayloadOrigin is an inline enum type for FeedbackPayload.Origin.
type FeedbackPayloadOrigin string

const (
	FeedbackPayloadOriginManualReview FeedbackPayloadOrigin = "manualReview"
	FeedbackPayloadOriginChargebacks FeedbackPayloadOrigin = "chargebacks"
	FeedbackPayloadOriginAutomatedRule FeedbackPayloadOrigin = "automatedRule"
	FeedbackPayloadOriginDashboard FeedbackPayloadOrigin = "dashboard"
	FeedbackPayloadOriginDatadome FeedbackPayloadOrigin = "datadome"
	FeedbackPayloadOriginOther FeedbackPayloadOrigin = "other"
)

// FeedbackPayload Feedback payload to provide to the feedback endpoint
type FeedbackPayload struct {
	// The decision that should have been taken for the event or account (mandatory).
	Decision FeedbackPayloadDecision `json:"decision"`
	// The timestamp (EPOCH in milliseconds) when the decision was taken.
	DecisionTime *int `json:"decisionTime,omitempty"`
	// The description of the reasons why a decision has been taken.
	DecisionReason *string `json:"decisionReason,omitempty"`
	// The system that triggers the decision (mandatory).
	Origin FeedbackPayloadOrigin `json:"origin"`
	// The id that identifies the decision-maker.
	OriginId *string `json:"originId,omitempty"`
	// The eventId of the event receiving a feedback. It should match the eventId returned by fraud SDK. This field is incompatible with account or userId but one of them is mandatory.
	EventId *string `json:"eventId,omitempty"`
	// The account of the user receiving a feedback. It should match the field account sent in fraud SDK request. This field is incompatible with eventId or userId but one of them is mandatory.
	Account *string `json:"account,omitempty"`
	// The userId of the user receiving a feedback. It should match the field userId sent in fraud SDK request. This field is incompatible with eventId or account but one of them is mandatory.
	UserId *string `json:"userId,omitempty"`
}

// FeedbackPayloadOption is a functional option for configuring optional [FeedbackPayload] fields.
type FeedbackPayloadOption func(*FeedbackPayload)

// FeedbackPayloadWithDecisionTime sets the optional DecisionTime field.
func FeedbackPayloadWithDecisionTime(val int) (FeedbackPayloadOption, error) {
	return func(p *FeedbackPayload) { p.DecisionTime = &val }, nil
}

// FeedbackPayloadWithDecisionReason sets the optional DecisionReason field.
func FeedbackPayloadWithDecisionReason(val string) (FeedbackPayloadOption, error) {
	return func(p *FeedbackPayload) { p.DecisionReason = &val }, nil
}

// FeedbackPayloadWithOriginId sets the optional OriginId field.
func FeedbackPayloadWithOriginId(val string) (FeedbackPayloadOption, error) {
	return func(p *FeedbackPayload) { p.OriginId = &val }, nil
}

// FeedbackPayloadWithEventId sets the optional EventId field.
func FeedbackPayloadWithEventId(val string) (FeedbackPayloadOption, error) {
	return func(p *FeedbackPayload) { p.EventId = &val }, nil
}

// FeedbackPayloadWithAccount sets the optional Account field.
func FeedbackPayloadWithAccount(val string) (FeedbackPayloadOption, error) {
	return func(p *FeedbackPayload) { p.Account = &val }, nil
}

// FeedbackPayloadWithUserId sets the optional UserId field.
func FeedbackPayloadWithUserId(val string) (FeedbackPayloadOption, error) {
	return func(p *FeedbackPayload) { p.UserId = &val }, nil
}


