/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// PasswordUpdatePayloadAllOfUser struct for PasswordUpdatePayloadAllOfUser
type PasswordUpdatePayloadAllOfUser struct {
	// A unique customer identifier from your system. It has to be the same for all other event sent
	Id string `json:"id"`
}

func sanitizePasswordUpdatePayloadAllOfUser(v *PasswordUpdatePayloadAllOfUser) {
	v.Id = truncateValue(PasswordUpdatePayloadAllOfUserId, v.Id)
}


