/*
Account Protect API

DataDome Account Protect API. Validate login, registration, account update, password update and custom events to detect and prevent account takeover, or collect events to enrich detection, and submit feedback on recommendations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// RegistrationPayloadStatus is an inline enum type for RegistrationPayload.Status.
type RegistrationPayloadStatus string

const (
	RegistrationPayloadStatusAttempted RegistrationPayloadStatus = "attempted"
	RegistrationPayloadStatusSucceeded RegistrationPayloadStatus = "succeeded"
	RegistrationPayloadStatusFailed RegistrationPayloadStatus = "failed"
)

// RegistrationPayloadFailReason is an inline enum type for RegistrationPayload.FailReason.
type RegistrationPayloadFailReason string

const (
	RegistrationPayloadFailReasonDuplicatedAccount RegistrationPayloadFailReason = "duplicatedAccount"
	RegistrationPayloadFailReasonInvalidMfa RegistrationPayloadFailReason = "invalidMfa"
	RegistrationPayloadFailReasonCancelled RegistrationPayloadFailReason = "cancelled"
	RegistrationPayloadFailReasonInternalBusinessRule RegistrationPayloadFailReason = "internalBusinessRule"
	RegistrationPayloadFailReasonTechnicalIssue RegistrationPayloadFailReason = "technicalIssue"
	RegistrationPayloadFailReasonOther RegistrationPayloadFailReason = "other"
)

// RegistrationPayload struct for RegistrationPayload
type RegistrationPayload struct {
	// User account (mail address, username, alias, login, ...)
	Account string `json:"account"`
	Module Module `json:"module"`
	Header Header `json:"header"`
	// For customers who sell their product as white label app, identify the partner using the solution to adapt detection models.
	PartnerId *string `json:"partnerId,omitempty"`
	// Date when the event occurred on your side, if you send it later than it happened (for example from a queue). Format ISO 8601 YYYY-MM-DDThh:mm:ss.sssTZD. DataDome uses it to order the events. If eventDate is absent or has an invalid format, DataDome uses module.requestTimeMicros instead, and the event is still processed.
	EventDate *string `json:"eventDate,omitempty"`
	// Custom business data fields for additional customer-specific information
	CustomFields []CustomField `json:"customFields,omitempty"`
	Session *Session `json:"session,omitempty"`
	// Status of the registration to be able to identify where are we in the account creation process (supports multi-step registration)
	Status *RegistrationPayloadStatus `json:"status,omitempty"`
	// Reason why the registration failed. Helps differentiate different types of fraud patterns.
	FailReason *RegistrationPayloadFailReason `json:"failReason,omitempty"`
	AccountType *AccountType `json:"accountType,omitempty"`
	User RegistrationPayloadAllOfUser `json:"user"`
	Authentication *RegistrationPayloadAllOfAuthentication `json:"authentication,omitempty"`
}

// RegistrationPayloadOption is a functional option for configuring optional [RegistrationPayload] fields.
type RegistrationPayloadOption func(*RegistrationPayload)

// RegistrationPayloadWithPartnerId sets the optional PartnerId field.
func RegistrationPayloadWithPartnerId(val string) (RegistrationPayloadOption, error) {
	val = truncateValue(RegistrationPayloadPartnerId, val)
	return func(p *RegistrationPayload) { p.PartnerId = &val }, nil
}

// RegistrationPayloadWithEventDate sets the optional EventDate field.
func RegistrationPayloadWithEventDate(val string) (RegistrationPayloadOption, error) {
	return func(p *RegistrationPayload) { p.EventDate = &val }, nil
}

// RegistrationPayloadWithCustomFields sets the optional CustomFields field.
func RegistrationPayloadWithCustomFields(val []CustomField) RegistrationPayloadOption {
	for i := range val {
		sanitizeCustomField(&val[i])
	}
	if len(val) > 10 {
		val = val[:10]
	}
	return func(p *RegistrationPayload) { p.CustomFields = val }
}
// RegistrationPayloadWithSession sets the optional Session field.
func RegistrationPayloadWithSession(val Session) (RegistrationPayloadOption, error) {
	sanitizeSession(&val)
	return func(p *RegistrationPayload) { p.Session = &val }, nil
}

// RegistrationPayloadWithStatus sets the optional Status field.
func RegistrationPayloadWithStatus(val RegistrationPayloadStatus) (RegistrationPayloadOption, error) {
	return func(p *RegistrationPayload) { p.Status = &val }, nil
}

// RegistrationPayloadWithFailReason sets the optional FailReason field.
func RegistrationPayloadWithFailReason(val RegistrationPayloadFailReason) (RegistrationPayloadOption, error) {
	return func(p *RegistrationPayload) { p.FailReason = &val }, nil
}

// RegistrationPayloadWithAccountType sets the optional AccountType field.
func RegistrationPayloadWithAccountType(val AccountType) (RegistrationPayloadOption, error) {
	return func(p *RegistrationPayload) { p.AccountType = &val }, nil
}

// RegistrationPayloadWithAuthentication sets the optional Authentication field.
func RegistrationPayloadWithAuthentication(val RegistrationPayloadAllOfAuthentication) (RegistrationPayloadOption, error) {
	return func(p *RegistrationPayload) { p.Authentication = &val }, nil
}


