/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo

import "fmt"
import "net/http"



// Header Header sent by the User to the Customer endpoint
type Header struct {
	// IP address of the originating host making the request (final client's IP address), HTTP_CLIENT_IP
	Addr string `json:"addr"`
	// Request content-type, CONTENT_TYPE
	ContentType string `json:"contentType"`
	// Request host, HTTP_HOST
	Host string `json:"host"`
	// Request port, REMOTE_PORT
	Port int `json:"port"`
	// HTTP_X_REAL_IP
	XRealIp string `json:"xRealIp"`
	// List of client and intermediate proxies/load-balancers IPs, HTTP_X_FORWARDED_FOR
	XForwardedForIp string `json:"xForwardedForIp"`
	// HTTP_ACCEPT_ENCODING
	AcceptEncoding string `json:"acceptEncoding"`
	// HTTP_ACCEPT_LANGUAGE
	AcceptLanguage string `json:"acceptLanguage"`
	// Contents of the Accept: header from the current request, if there is one, HTTP_ACCEPT
	Accept string `json:"accept"`
	// HTTP method (GET/POST/OPTION), REQUEST_METHOD
	Method string `json:"method"`
	// Scheme part of the Request-URI (HTTP or HTTPS), SERVER_PROTOCOL
	Protocol string `json:"protocol"`
	// Virtual host, SERVER_NAME
	ServerHostname string `json:"serverHostname"`
	// HTTP_REFERER
	Referer string `json:"referer"`
	// HTTP_USER_AGENT
	UserAgent string `json:"userAgent"`
	// HTTP_FROM
	From string `json:"from"`
	// Path and query part of the Request-URI, REQUEST_URI
	Request string `json:"request"`
	// ORIG_PATH_INFO
	Origin string `json:"origin"`
	// HTTP_ACCEPT_CHARSET
	AcceptCharset string `json:"acceptCharset"`
	// Check Keep-Alive, from request Header if present, HTTP_CONNECTION
	Connection string `json:"connection"`
	// The value of the datadome cookie attached to the client request
	ClientID string `json:"clientID"`
	// Client hint providing the user-agent's branding and significant version information
	SecCHUA *string `json:"secCHUA,omitempty"`
	// Client hint for indicating whether the browser is on a mobile device
	SecCHUAMobile *string `json:"secCHUAMobile,omitempty"`
	// Client hint for indicating the platform or operating system on which the user agent is running
	SecCHUAPlatform *string `json:"secCHUAPlatform,omitempty"`
	// Client hint for indicating the user-agent's underlying CPU architecture, such as ARM or x86
	SecCHUAArch *string `json:"secCHUAArch,omitempty"`
	// Client hint for indicating the user-agent's branding and full version information
	SecCHUAFullVersionList *string `json:"secCHUAFullVersionList,omitempty"`
	// Client hint for indicating the device model on which the browser is running
	SecCHUAModel *string `json:"secCHUAModel,omitempty"`
	// Client hint for indicating the approximate amount of available RAM on the client device
	SecCHDeviceMemory *string `json:"secCHDeviceMemory,omitempty"`
}
// RequestMetadata contains optional HTTP request metadata fields.
// Each field overrides the value automatically extracted from the incoming HTTP request.
type RequestMetadata struct {
	// IP address of the originating host making the request (final client's IP address), HTTP_CLIENT_IP
	Addr *string `json:"addr"`
	// Request content-type, CONTENT_TYPE
	ContentType *string `json:"contentType"`
	// Request host, HTTP_HOST
	Host *string `json:"host"`
	// Request port, REMOTE_PORT
	Port *int `json:"port"`
	// HTTP_X_REAL_IP
	XRealIp *string `json:"xRealIp"`
	// List of client and intermediate proxies/load-balancers IPs, HTTP_X_FORWARDED_FOR
	XForwardedForIp *string `json:"xForwardedForIp"`
	// HTTP_ACCEPT_ENCODING
	AcceptEncoding *string `json:"acceptEncoding"`
	// HTTP_ACCEPT_LANGUAGE
	AcceptLanguage *string `json:"acceptLanguage"`
	// Contents of the Accept: header from the current request, if there is one, HTTP_ACCEPT
	Accept *string `json:"accept"`
	// HTTP method (GET/POST/OPTION), REQUEST_METHOD
	Method *string `json:"method"`
	// Scheme part of the Request-URI (HTTP or HTTPS), SERVER_PROTOCOL
	Protocol *string `json:"protocol"`
	// Virtual host, SERVER_NAME
	ServerHostname *string `json:"serverHostname"`
	// HTTP_REFERER
	Referer *string `json:"referer"`
	// HTTP_USER_AGENT
	UserAgent *string `json:"userAgent"`
	// HTTP_FROM
	From *string `json:"from"`
	// Path and query part of the Request-URI, REQUEST_URI
	Request *string `json:"request"`
	// ORIG_PATH_INFO
	Origin *string `json:"origin"`
	// HTTP_ACCEPT_CHARSET
	AcceptCharset *string `json:"acceptCharset"`
	// Check Keep-Alive, from request Header if present, HTTP_CONNECTION
	Connection *string `json:"connection"`
	// The value of the datadome cookie attached to the client request
	ClientID *string `json:"clientID"`
	// Client hint providing the user-agent's branding and significant version information
	SecCHUA *string `json:"secCHUA,omitempty"`
	// Client hint for indicating whether the browser is on a mobile device
	SecCHUAMobile *string `json:"secCHUAMobile,omitempty"`
	// Client hint for indicating the platform or operating system on which the user agent is running
	SecCHUAPlatform *string `json:"secCHUAPlatform,omitempty"`
	// Client hint for indicating the user-agent's underlying CPU architecture, such as ARM or x86
	SecCHUAArch *string `json:"secCHUAArch,omitempty"`
	// Client hint for indicating the user-agent's branding and full version information
	SecCHUAFullVersionList *string `json:"secCHUAFullVersionList,omitempty"`
	// Client hint for indicating the device model on which the browser is running
	SecCHUAModel *string `json:"secCHUAModel,omitempty"`
	// Client hint for indicating the approximate amount of available RAM on the client device
	SecCHDeviceMemory *string `json:"secCHDeviceMemory,omitempty"`
}


func sanitizeHeader(v *Header) {
	v.ContentType = truncateValue(HeaderContentType, v.ContentType)
	v.Host = truncateValue(HeaderHost, v.Host)
	v.XRealIp = truncateValue(HeaderXRealIp, v.XRealIp)
	v.XForwardedForIp = truncateValue(HeaderXForwardedForIp, v.XForwardedForIp)
	v.AcceptEncoding = truncateValue(HeaderAcceptEncoding, v.AcceptEncoding)
	v.AcceptLanguage = truncateValue(HeaderAcceptLanguage, v.AcceptLanguage)
	v.Accept = truncateValue(HeaderAccept, v.Accept)
	v.ServerHostname = truncateValue(HeaderServerHostname, v.ServerHostname)
	v.Referer = truncateValue(HeaderReferer, v.Referer)
	v.UserAgent = truncateValue(HeaderUserAgent, v.UserAgent)
	v.From = truncateValue(HeaderFrom, v.From)
	v.Request = truncateValue(HeaderRequest, v.Request)
	v.Origin = truncateValue(HeaderOrigin, v.Origin)
	v.AcceptCharset = truncateValue(HeaderAcceptCharset, v.AcceptCharset)
	v.Connection = truncateValue(HeaderConnection, v.Connection)
	v.ClientID = truncateValue(HeaderClientID, v.ClientID)
	v.SecCHUA = truncatePointerValue(HeaderSecCHUA, v.SecCHUA)
	v.SecCHUAMobile = truncatePointerValue(HeaderSecCHUAMobile, v.SecCHUAMobile)
	v.SecCHUAPlatform = truncatePointerValue(HeaderSecCHUAPlatform, v.SecCHUAPlatform)
	v.SecCHUAArch = truncatePointerValue(HeaderSecCHUAArch, v.SecCHUAArch)
	v.SecCHUAFullVersionList = truncatePointerValue(HeaderSecCHUAFullVersionList, v.SecCHUAFullVersionList)
	v.SecCHUAModel = truncatePointerValue(HeaderSecCHUAModel, v.SecCHUAModel)
	v.SecCHDeviceMemory = truncatePointerValue(HeaderSecCHDeviceMemory, v.SecCHDeviceMemory)
}


// buildHeader is used to construct the [Header] type.
// It constructs this payload by reading the [RequestMetadata] fields if specified.
// It will extract the information from the incoming request otherwise.
//
// An error may be returned if the IP cannot be retrieved.
func buildHeader(r *http.Request, rm *RequestMetadata) (*Header, error) {
	var proto string
	if rm.Protocol != nil {
		proto = *rm.Protocol
	} else {
		proto = getProtocol(r)
	}

	var ip string
	if rm.Addr != nil {
		ip = *rm.Addr
	} else {
		userIp, err := getIP(r)
		if err != nil {
			return nil, fmt.Errorf("fail to parse request's IP: %w", err)
		}
		ip = userIp
	}

	port := useMetadata(getPort(r), rm.Port)
	if port == -1 {
		if proto == "https" {
			port = 443
		} else {
			port = 80
		}
	}

	secCHUA := useMetadata(r.Header.Get("sec-ch-ua"), rm.SecCHUA)
	secCHUAMobile := useMetadata(r.Header.Get("sec-ch-ua-mobile"), rm.SecCHUAMobile)
	secCHUAPlatform := useMetadata(r.Header.Get("sec-ch-ua-platform"), rm.SecCHUAPlatform)
	secCHUAArch := useMetadata(r.Header.Get("sec-ch-ua-arch"), rm.SecCHUAArch)
	secCHUAFullVersionList := useMetadata(r.Header.Get("sec-ch-ua-full-version-list"), rm.SecCHUAFullVersionList)
	secCHUAModel := useMetadata(r.Header.Get("sec-ch-ua-model"), rm.SecCHUAModel)
	secCHDeviceMemory := useMetadata(r.Header.Get("sec-ch-device-memory"), rm.SecCHDeviceMemory)

	return &Header{
		Addr:           ip,
		Method:         r.Method,
		Port:           port,
		Protocol:       proto,
		ClientID:       getClientId(r),
		Host:           r.Host,
		Request:        getURL(r),
		ServerHostname: r.Host,
		ContentType: truncateValue(HeaderContentType, useMetadata(r.Header.Get("content-type"), rm.ContentType)),
		XRealIp: truncateValue(HeaderXRealIp, useMetadata(r.Header.Get("x-real-ip"), rm.XRealIp)),
		XForwardedForIp: truncateValue(HeaderXForwardedForIp, useMetadata(r.Header.Get("x-forwarded-for"), rm.XForwardedForIp)),
		AcceptEncoding: truncateValue(HeaderAcceptEncoding, useMetadata(r.Header.Get("accept-encoding"), rm.AcceptEncoding)),
		AcceptLanguage: truncateValue(HeaderAcceptLanguage, useMetadata(r.Header.Get("accept-language"), rm.AcceptLanguage)),
		Accept: truncateValue(HeaderAccept, useMetadata(r.Header.Get("accept"), rm.Accept)),
		Referer: truncateValue(HeaderReferer, useMetadata(r.Header.Get("referer"), rm.Referer)),
		UserAgent: truncateValue(HeaderUserAgent, useMetadata(r.Header.Get("user-agent"), rm.UserAgent)),
		From: truncateValue(HeaderFrom, useMetadata(r.Header.Get("from"), rm.From)),
		Origin: truncateValue(HeaderOrigin, useMetadata(r.Header.Get("origin"), rm.Origin)),
		AcceptCharset: truncateValue(HeaderAcceptCharset, useMetadata(r.Header.Get("accept-charset"), rm.AcceptCharset)),
		Connection: truncateValue(HeaderConnection, useMetadata(r.Header.Get("connection"), rm.Connection)),
		SecCHUA: truncatePointerValue(HeaderSecCHUA, &secCHUA),
		SecCHUAMobile: truncatePointerValue(HeaderSecCHUAMobile, &secCHUAMobile),
		SecCHUAPlatform: truncatePointerValue(HeaderSecCHUAPlatform, &secCHUAPlatform),
		SecCHUAArch: truncatePointerValue(HeaderSecCHUAArch, &secCHUAArch),
		SecCHUAFullVersionList: truncatePointerValue(HeaderSecCHUAFullVersionList, &secCHUAFullVersionList),
		SecCHUAModel: truncatePointerValue(HeaderSecCHUAModel, &secCHUAModel),
		SecCHDeviceMemory: truncatePointerValue(HeaderSecCHDeviceMemory, &secCHDeviceMemory),
	}, nil
}
