/*
Account Protect API

DataDome Account Protect API. Validate login, registration, account update, password update and custom events to detect and prevent account takeover, or collect events to enrich detection, and submit feedback on recommendations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// CustomActionPayloadBaseEventStatus is an inline enum type for CustomActionPayloadBase.EventStatus.
type CustomActionPayloadBaseEventStatus string

const (
	CustomActionPayloadBaseEventStatusAttempted CustomActionPayloadBaseEventStatus = "attempted"
	CustomActionPayloadBaseEventStatusSucceeded CustomActionPayloadBaseEventStatus = "succeeded"
	CustomActionPayloadBaseEventStatusFailed CustomActionPayloadBaseEventStatus = "failed"
	CustomActionPayloadBaseEventStatusExpired CustomActionPayloadBaseEventStatus = "expired"
)

// CustomActionPayloadBase Base properties for custom event payload sent from Customer endpoint to Account Protect server
type CustomActionPayloadBase struct {
	Module Module `json:"module"`
	Header Header `json:"header"`
	// For customers who sell their product as white label app, identify the partner using the solution to adapt detection models.
	PartnerId *string `json:"partnerId,omitempty"`
	// Date when the event occurred on your side, if you send it later than it happened (for example from a queue). Format ISO 8601 YYYY-MM-DDThh:mm:ss.sssTZD. DataDome uses it to order the events. If eventDate is absent or has an invalid format, DataDome uses module.requestTimeMicros instead, and the event is still processed.
	EventDate *string `json:"eventDate,omitempty"`
	// Custom business data fields for additional customer-specific information
	CustomFields []CustomField `json:"customFields,omitempty"`
	// Name of the custom event in camelCase.
	EventName string `json:"eventName"`
	// Status of the custom event.
	EventStatus *CustomActionPayloadBaseEventStatus `json:"eventStatus,omitempty"`
	// `true`: the action is linked to a sensitive behavior. `false` (default): the action is NOT linked to a sensitive behavior.
	IsEventCritical *bool `json:"isEventCritical,omitempty"`
	// Any raw text provided by the user. It can be a message content, a post, a ticket or any other relevant data to be checked by Account Protect. Content longer than 24544 bytes (UTF-8) is trimmed before storage. (PII)
	Content *string `json:"content,omitempty"`
	// The account related to the action. For example, if user A sends a message to user B, the value will be B. (PII)
	AccountTarget *string `json:"accountTarget,omitempty"`
	Session *Session `json:"session,omitempty"`
	AccountType *AccountType `json:"accountType,omitempty"`
	// Date when account was created. Help improve detection for account created before Account Protect setup. Format ISO 8601 YYYY-MM-DDThh:mm:ssTZD
	AccountCreationDate *string `json:"accountCreationDate,omitempty"`
	Authentication *Authentication `json:"authentication,omitempty"`
}

func sanitizeCustomActionPayloadBase(v *CustomActionPayloadBase) {
	sanitizeHeader(&v.Header)
	v.PartnerId = truncatePointerValue(CustomActionPayloadBasePartnerId, v.PartnerId)
	if len(v.CustomFields) > 10 {
		v.CustomFields = v.CustomFields[:10]
	}
	for i := range v.CustomFields {
		sanitizeCustomField(&v.CustomFields[i])
	}
	v.EventName = truncateValue(CustomActionPayloadBaseEventName, v.EventName)
	v.Content = truncatePointerValue(CustomActionPayloadBaseContent, v.Content)
	v.AccountTarget = truncatePointerValue(CustomActionPayloadBaseAccountTarget, v.AccountTarget)
	if v.Session != nil {
		sanitizeSession(v.Session)
	}
}


