/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo




// CustomFieldType is an inline enum type for CustomField.Type.
type CustomFieldType string

const (
	CustomFieldTypeString CustomFieldType = "string"
	CustomFieldTypePhone CustomFieldType = "phone"
	CustomFieldTypeEmail CustomFieldType = "email"
	CustomFieldTypeUserId CustomFieldType = "userId"
	CustomFieldTypeNumber CustomFieldType = "number"
	CustomFieldTypeIp CustomFieldType = "ip"
)

// CustomField Custom field for additional business data
type CustomField struct {
	// The name of the custom data field. Cannot be null or empty.
	Name string `json:"name"`
	// The value of the custom data field. Can be empty but not null.
	Value string `json:"value"`
	// Data type for the custom field. Default is String.
	Type *CustomFieldType `json:"type,omitempty"`
	// Indicates whether this field contains PII (Personally Identifiable Information). Default is false.
	IsPii *bool `json:"isPii,omitempty"`
}

func sanitizeCustomField(v *CustomField) {
	v.Name = truncateValue(CustomFieldName, v.Name)
	v.Value = truncateValue(CustomFieldValue, v.Value)
}


