/*
Fraud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fraudsdkgo

import (
	"net"
	"net/http"
	"strconv"
	"strings"
)

// ApiFields describes the fields for which a size constraint is applied.
type ApiFields string

// Field constants derived from the OpenAPI spec maxLength constraints.
// Named as <Model><Field> to guarantee uniqueness across all schemas.
const (
	AccountUpdatePayloadAccount ApiFields = "AccountUpdatePayload.account"
	AccountUpdatePayloadPartnerId ApiFields = "AccountUpdatePayload.partnerId"
	AccountUpdatePayloadAllOfUserId ApiFields = "AccountUpdatePayloadAllOfUser.id"
	AccountUpdatePayloadAllOfUserFirstName ApiFields = "AccountUpdatePayloadAllOfUser.firstName"
	AccountUpdatePayloadAllOfUserLastName ApiFields = "AccountUpdatePayloadAllOfUser.lastName"
	AccountUpdatePayloadAllOfUserPhone ApiFields = "AccountUpdatePayloadAllOfUser.phone"
	AccountUpdatePayloadAllOfUserEmail ApiFields = "AccountUpdatePayloadAllOfUser.email"
	AccountUpdatePayloadAllOfUserDisplayName ApiFields = "AccountUpdatePayloadAllOfUser.displayName"
	AccountUpdatePayloadAllOfUserDescription ApiFields = "AccountUpdatePayloadAllOfUser.description"
	CustomActionPayloadPartnerId ApiFields = "CustomActionPayload.partnerId"
	CustomActionPayloadEventName ApiFields = "CustomActionPayload.eventName"
	CustomActionPayloadContent ApiFields = "CustomActionPayload.content"
	CustomActionPayloadAccountTarget ApiFields = "CustomActionPayload.accountTarget"
	CustomActionPayloadAccount ApiFields = "CustomActionPayload.account"
	CustomActionPayloadAnyOfPartnerId ApiFields = "CustomActionPayloadAnyOf.partnerId"
	CustomActionPayloadAnyOfEventName ApiFields = "CustomActionPayloadAnyOf.eventName"
	CustomActionPayloadAnyOfContent ApiFields = "CustomActionPayloadAnyOf.content"
	CustomActionPayloadAnyOfAccountTarget ApiFields = "CustomActionPayloadAnyOf.accountTarget"
	CustomActionPayloadAnyOfAccount ApiFields = "CustomActionPayloadAnyOf.account"
	CustomActionPayloadAnyOf1PartnerId ApiFields = "CustomActionPayloadAnyOf1.partnerId"
	CustomActionPayloadAnyOf1EventName ApiFields = "CustomActionPayloadAnyOf1.eventName"
	CustomActionPayloadAnyOf1Content ApiFields = "CustomActionPayloadAnyOf1.content"
	CustomActionPayloadAnyOf1AccountTarget ApiFields = "CustomActionPayloadAnyOf1.accountTarget"
	CustomActionPayloadAnyOf1AllOfUserId ApiFields = "CustomActionPayloadAnyOf1AllOfUser.id"
	CustomActionPayloadAnyOf1AllOfUserFirstName ApiFields = "CustomActionPayloadAnyOf1AllOfUser.firstName"
	CustomActionPayloadAnyOf1AllOfUserLastName ApiFields = "CustomActionPayloadAnyOf1AllOfUser.lastName"
	CustomActionPayloadAnyOf1AllOfUserPhone ApiFields = "CustomActionPayloadAnyOf1AllOfUser.phone"
	CustomActionPayloadAnyOf1AllOfUserEmail ApiFields = "CustomActionPayloadAnyOf1AllOfUser.email"
	CustomActionPayloadAnyOf1AllOfUserDisplayName ApiFields = "CustomActionPayloadAnyOf1AllOfUser.displayName"
	CustomActionPayloadAnyOf1AllOfUserDescription ApiFields = "CustomActionPayloadAnyOf1AllOfUser.description"
	CustomActionPayloadBasePartnerId ApiFields = "CustomActionPayloadBase.partnerId"
	CustomActionPayloadBaseEventName ApiFields = "CustomActionPayloadBase.eventName"
	CustomActionPayloadBaseContent ApiFields = "CustomActionPayloadBase.content"
	CustomActionPayloadBaseAccountTarget ApiFields = "CustomActionPayloadBase.accountTarget"
	CustomFieldName ApiFields = "CustomField.name"
	CustomFieldValue ApiFields = "CustomField.value"
	HeaderContentType ApiFields = "Header.contentType"
	HeaderHost ApiFields = "Header.host"
	HeaderXRealIp ApiFields = "Header.xRealIp"
	HeaderXForwardedForIp ApiFields = "Header.xForwardedForIp"
	HeaderAcceptEncoding ApiFields = "Header.acceptEncoding"
	HeaderAcceptLanguage ApiFields = "Header.acceptLanguage"
	HeaderAccept ApiFields = "Header.accept"
	HeaderServerHostname ApiFields = "Header.serverHostname"
	HeaderReferer ApiFields = "Header.referer"
	HeaderUserAgent ApiFields = "Header.userAgent"
	HeaderFrom ApiFields = "Header.from"
	HeaderRequest ApiFields = "Header.request"
	HeaderOrigin ApiFields = "Header.origin"
	HeaderAcceptCharset ApiFields = "Header.acceptCharset"
	HeaderConnection ApiFields = "Header.connection"
	HeaderClientID ApiFields = "Header.clientID"
	HeaderSecCHUA ApiFields = "Header.secCHUA"
	HeaderSecCHUAMobile ApiFields = "Header.secCHUAMobile"
	HeaderSecCHUAPlatform ApiFields = "Header.secCHUAPlatform"
	HeaderSecCHUAArch ApiFields = "Header.secCHUAArch"
	HeaderSecCHUAFullVersionList ApiFields = "Header.secCHUAFullVersionList"
	HeaderSecCHUAModel ApiFields = "Header.secCHUAModel"
	HeaderSecCHDeviceMemory ApiFields = "Header.secCHDeviceMemory"
	LoginPayloadAccount ApiFields = "LoginPayload.account"
	LoginPayloadPartnerId ApiFields = "LoginPayload.partnerId"
	LoginPayloadAllOfUserId ApiFields = "LoginPayloadAllOfUser.id"
	PasswordUpdatePayloadAccount ApiFields = "PasswordUpdatePayload.account"
	PasswordUpdatePayloadPartnerId ApiFields = "PasswordUpdatePayload.partnerId"
	PasswordUpdatePayloadAllOfUserId ApiFields = "PasswordUpdatePayloadAllOfUser.id"
	PayloadAccount ApiFields = "Payload.account"
	PayloadPartnerId ApiFields = "Payload.partnerId"
	RegistrationPayloadAccount ApiFields = "RegistrationPayload.account"
	RegistrationPayloadPartnerId ApiFields = "RegistrationPayload.partnerId"
	RegistrationPayloadAllOfUserId ApiFields = "RegistrationPayloadAllOfUser.id"
	RegistrationPayloadAllOfUserFirstName ApiFields = "RegistrationPayloadAllOfUser.firstName"
	RegistrationPayloadAllOfUserLastName ApiFields = "RegistrationPayloadAllOfUser.lastName"
	RegistrationPayloadAllOfUserPhone ApiFields = "RegistrationPayloadAllOfUser.phone"
	RegistrationPayloadAllOfUserEmail ApiFields = "RegistrationPayloadAllOfUser.email"
	RegistrationPayloadAllOfUserDisplayName ApiFields = "RegistrationPayloadAllOfUser.displayName"
	RegistrationPayloadAllOfUserDescription ApiFields = "RegistrationPayloadAllOfUser.description"
	SessionId ApiFields = "Session.id"
	UserFirstName ApiFields = "User.firstName"
	UserLastName ApiFields = "User.lastName"
	UserPhone ApiFields = "User.phone"
	UserEmail ApiFields = "User.email"
	UserDisplayName ApiFields = "User.displayName"
	UserDescription ApiFields = "User.description"
	UserAllOfAddressName ApiFields = "UserAllOfAddress.name"
	UserAllOfAddressLine1 ApiFields = "UserAllOfAddress.line1"
	UserAllOfAddressLine2 ApiFields = "UserAllOfAddress.line2"
	UserAllOfAddressCity ApiFields = "UserAllOfAddress.city"
	UserAllOfAddressCountryCode ApiFields = "UserAllOfAddress.countryCode"
	UserAllOfAddressRegionCode ApiFields = "UserAllOfAddress.regionCode"
	UserAllOfAddressZipCode ApiFields = "UserAllOfAddress.zipCode"
	UserIdId ApiFields = "UserId.id"
)

// maxItems constants derived from the OpenAPI spec maxItems constraints.
const (
	MaxAccountUpdatePayloadCustomFields = 10
	MaxAccountUpdatePayloadAllOfUserPictureUrls = 10
	MaxAccountUpdatePayloadAllOfUserExternalUrls = 10
	MaxCustomActionPayloadCustomFields = 10
	MaxCustomActionPayloadAnyOfCustomFields = 10
	MaxCustomActionPayloadAnyOf1CustomFields = 10
	MaxCustomActionPayloadAnyOf1AllOfUserPictureUrls = 10
	MaxCustomActionPayloadAnyOf1AllOfUserExternalUrls = 10
	MaxCustomActionPayloadBaseCustomFields = 10
	MaxLoginPayloadCustomFields = 10
	MaxPasswordUpdatePayloadCustomFields = 10
	MaxPayloadCustomFields = 10
	MaxRegistrationPayloadCustomFields = 10
	MaxRegistrationPayloadAllOfUserPictureUrls = 10
	MaxRegistrationPayloadAllOfUserExternalUrls = 10
	MaxUserPictureUrls = 10
	MaxUserExternalUrls = 10
)

// Array-item string truncation constants derived from the OpenAPI spec items.maxLength constraints.
const (
	AccountUpdatePayloadAllOfUserPictureUrlsItem ApiFields = "AccountUpdatePayloadAllOfUser.pictureUrls[*]"
	AccountUpdatePayloadAllOfUserExternalUrlsItem ApiFields = "AccountUpdatePayloadAllOfUser.externalUrls[*]"
	CustomActionPayloadAnyOf1AllOfUserPictureUrlsItem ApiFields = "CustomActionPayloadAnyOf1AllOfUser.pictureUrls[*]"
	CustomActionPayloadAnyOf1AllOfUserExternalUrlsItem ApiFields = "CustomActionPayloadAnyOf1AllOfUser.externalUrls[*]"
	RegistrationPayloadAllOfUserPictureUrlsItem ApiFields = "RegistrationPayloadAllOfUser.pictureUrls[*]"
	RegistrationPayloadAllOfUserExternalUrlsItem ApiFields = "RegistrationPayloadAllOfUser.externalUrls[*]"
	UserPictureUrlsItem ApiFields = "User.pictureUrls[*]"
	UserExternalUrlsItem ApiFields = "User.externalUrls[*]"
)

// getTruncationSize returns the maximum allowed size for a given [ApiFields].
// A negative value means the content is truncated from the start (the end of the string is preserved).
func getTruncationSize(key ApiFields) int {
	switch key {
	case AccountUpdatePayloadAccount:
		return 320
	case AccountUpdatePayloadPartnerId:
		return 320
	case AccountUpdatePayloadAllOfUserId:
		return 320
	case AccountUpdatePayloadAllOfUserFirstName:
		return 50
	case AccountUpdatePayloadAllOfUserLastName:
		return 50
	case AccountUpdatePayloadAllOfUserPhone:
		return 16
	case AccountUpdatePayloadAllOfUserEmail:
		return 320
	case AccountUpdatePayloadAllOfUserDisplayName:
		return 100
	case AccountUpdatePayloadAllOfUserDescription:
		return 320
	case CustomActionPayloadPartnerId:
		return 320
	case CustomActionPayloadEventName:
		return 20
	case CustomActionPayloadContent:
		return 24544
	case CustomActionPayloadAccountTarget:
		return 320
	case CustomActionPayloadAccount:
		return 320
	case CustomActionPayloadAnyOfPartnerId:
		return 320
	case CustomActionPayloadAnyOfEventName:
		return 20
	case CustomActionPayloadAnyOfContent:
		return 24544
	case CustomActionPayloadAnyOfAccountTarget:
		return 320
	case CustomActionPayloadAnyOfAccount:
		return 320
	case CustomActionPayloadAnyOf1PartnerId:
		return 320
	case CustomActionPayloadAnyOf1EventName:
		return 20
	case CustomActionPayloadAnyOf1Content:
		return 24544
	case CustomActionPayloadAnyOf1AccountTarget:
		return 320
	case CustomActionPayloadAnyOf1AllOfUserId:
		return 320
	case CustomActionPayloadAnyOf1AllOfUserFirstName:
		return 50
	case CustomActionPayloadAnyOf1AllOfUserLastName:
		return 50
	case CustomActionPayloadAnyOf1AllOfUserPhone:
		return 16
	case CustomActionPayloadAnyOf1AllOfUserEmail:
		return 320
	case CustomActionPayloadAnyOf1AllOfUserDisplayName:
		return 100
	case CustomActionPayloadAnyOf1AllOfUserDescription:
		return 320
	case CustomActionPayloadBasePartnerId:
		return 320
	case CustomActionPayloadBaseEventName:
		return 20
	case CustomActionPayloadBaseContent:
		return 24544
	case CustomActionPayloadBaseAccountTarget:
		return 320
	case CustomFieldName:
		return 25
	case CustomFieldValue:
		return 1024
	case HeaderContentType:
		return 64
	case HeaderHost:
		return 512
	case HeaderXRealIp:
		return 128
	case HeaderXForwardedForIp:
		return -512
	case HeaderAcceptEncoding:
		return 128
	case HeaderAcceptLanguage:
		return 256
	case HeaderAccept:
		return 512
	case HeaderServerHostname:
		return 512
	case HeaderReferer:
		return 1024
	case HeaderUserAgent:
		return 768
	case HeaderFrom:
		return 128
	case HeaderRequest:
		return 2048
	case HeaderOrigin:
		return 512
	case HeaderAcceptCharset:
		return 128
	case HeaderConnection:
		return 128
	case HeaderClientID:
		return 512
	case HeaderSecCHUA:
		return 128
	case HeaderSecCHUAMobile:
		return 8
	case HeaderSecCHUAPlatform:
		return 32
	case HeaderSecCHUAArch:
		return 16
	case HeaderSecCHUAFullVersionList:
		return 256
	case HeaderSecCHUAModel:
		return 128
	case HeaderSecCHDeviceMemory:
		return 8
	case LoginPayloadAccount:
		return 320
	case LoginPayloadPartnerId:
		return 320
	case LoginPayloadAllOfUserId:
		return 320
	case PasswordUpdatePayloadAccount:
		return 320
	case PasswordUpdatePayloadPartnerId:
		return 320
	case PasswordUpdatePayloadAllOfUserId:
		return 320
	case PayloadAccount:
		return 320
	case PayloadPartnerId:
		return 320
	case RegistrationPayloadAccount:
		return 320
	case RegistrationPayloadPartnerId:
		return 320
	case RegistrationPayloadAllOfUserId:
		return 320
	case RegistrationPayloadAllOfUserFirstName:
		return 50
	case RegistrationPayloadAllOfUserLastName:
		return 50
	case RegistrationPayloadAllOfUserPhone:
		return 16
	case RegistrationPayloadAllOfUserEmail:
		return 320
	case RegistrationPayloadAllOfUserDisplayName:
		return 100
	case RegistrationPayloadAllOfUserDescription:
		return 320
	case SessionId:
		return 255
	case UserFirstName:
		return 50
	case UserLastName:
		return 50
	case UserPhone:
		return 16
	case UserEmail:
		return 320
	case UserDisplayName:
		return 100
	case UserDescription:
		return 320
	case UserAllOfAddressName:
		return 50
	case UserAllOfAddressLine1:
		return 255
	case UserAllOfAddressLine2:
		return 255
	case UserAllOfAddressCity:
		return 255
	case UserAllOfAddressCountryCode:
		return 2
	case UserAllOfAddressRegionCode:
		return 15
	case UserAllOfAddressZipCode:
		return 15
	case UserIdId:
		return 320
	case AccountUpdatePayloadAllOfUserPictureUrlsItem:
		return 2048
	case AccountUpdatePayloadAllOfUserExternalUrlsItem:
		return 2048
	case CustomActionPayloadAnyOf1AllOfUserPictureUrlsItem:
		return 2048
	case CustomActionPayloadAnyOf1AllOfUserExternalUrlsItem:
		return 2048
	case RegistrationPayloadAllOfUserPictureUrlsItem:
		return 2048
	case RegistrationPayloadAllOfUserExternalUrlsItem:
		return 2048
	case UserPictureUrlsItem:
		return 2048
	case UserExternalUrlsItem:
		return 2048
	}
	return 0
}

// truncateValue returns the truncated value of the given key.
// If the value does not need to be truncated, it remains unchanged.
func truncateValue(key ApiFields, value string) string {
	if value == "" {
		return ""
	}

	limit := getTruncationSize(key)
	runes := []rune(value)
	if limit < 0 && len(runes) > (-1*limit) {
		limit *= -1
		value = string(runes[len(runes)-limit:])
	} else if limit > 0 && len(runes) > limit {
		value = string(runes[:limit])
	}

	return value
}

// truncatePointerValue returns a pointer of the truncated value of the given key.
// If the value does not need to be truncated, it remains unchanged.
// Returns nil if value is nil or points to an empty string.
func truncatePointerValue(key ApiFields, value *string) *string {
	if value == nil || *value == "" {
		return nil
	}
	truncated := truncateValue(key, *value)
	return &truncated
}

// capAndTruncateStrings caps a string slice to maxItems and truncates each element to the size defined by key.
func capAndTruncateStrings(items []string, maxItems int, key ApiFields) []string {
	if items == nil {
		return nil
	}
	if len(items) > maxItems {
		items = items[:maxItems]
	}
	result := make([]string, len(items))
	for i, s := range items {
		result[i] = truncateValue(key, s)
	}
	return result
}

// getClientId retrieves the ClientID from the incoming request.
// It uses the value of the `X-DataDome-ClientID` if the session by header feature is used.
// It reads the `DataDome` cookie value otherwise.
func getClientId(r *http.Request) string {
	clientIDHeaders := r.Header.Get("x-datadome-clientid")
	if len(clientIDHeaders) > 0 {
		return clientIDHeaders
	}

	cookie, err := r.Cookie("datadome")
	if err == nil {
		return cookie.Value
	}

	return ""
}

// getIP returns the IP of the emitter from the RemoteAddr field of the request.
func getIP(r *http.Request) (string, error) {
	ip, _, err := net.SplitHostPort(r.RemoteAddr)
	return ip, err
}

// getProtocol returns the protocol of the request.
// It uses the `X-Forwarded-Proto` header value if the value is correct (i.e. `http` or `https`).
// It checks the TLS field of the request afterwards.
func getProtocol(r *http.Request) string {
	proto := "http"
	xForwardedProto := r.Header.Get("x-forwarded-proto")
	if strings.EqualFold(xForwardedProto, "http") || strings.EqualFold(xForwardedProto, "https") {
		proto = strings.ToLower(xForwardedProto)
	} else if r.TLS != nil {
		proto = "https"
	}

	return proto
}

// getURL returns the path and the query parameters (if present) of the request
func getURL(r *http.Request) string {
	if r.URL.RawQuery != "" {
		return r.URL.Path + "?" + r.URL.RawQuery
	} else {
		return r.URL.Path
	}
}

// getPort returns the port requested
func getPort(r *http.Request) int {
	if r.Host == "" {
		return -1
	}
	_, stringPort, err := net.SplitHostPort(r.Host)
	if err != nil {
		return -1
	}
	port, err := strconv.Atoi(stringPort)
	if err != nil {
		return -1
	}
	return port
}

// useMetadata returns the value of val2 if not nil.
// It returns val1 otherwise.
func useMetadata[T comparable](val1 T, val2 *T) T {
	if val2 != nil {
		return *val2
	}
	return val1
}
